### ISSUE TITLE
No Sign in to Twitter

### ISSUE THREAD

**Issue by the-clubbers** [lucahammer/WischWasch#2]
When i want to login the following error apears:
_Something went wrong with sign in. Please try again._
Maybe there ist a Twitter-API mismatch as of your version?

**Comment by lucahammer** [comment]
Hi. I didn't know that the app is still used. The Twitter API now require a callback in the API settings. I added it to make the tool work again. I don't have time to fix the other issues at the moment and am thinking about taking it offline.

**Comment by the-clubbers** [comment]
Ok, now it works - thanks
